version: "3.8"

services:
  dashboard:
    build:
      context: .
      dockerfile: dashboard/Dockerfile
    container_name: cwe770-dashboard
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  vulnerable:
    build: ./vulnerable
    container_name: cwe770-vulnerable
    ports:
      - "5000:5000"
    mem_limit: 256m
    memswap_limit: 256m   # = mem_limit -> sin swap
    mem_swappiness: 0
    volumes:
      - vulnerable_data:/data/uploads

  fixed:
    build: ./fixed
    container_name: cwe770-fixed
    ports:
      - "5001:5000"
    mem_limit: 256m
    memswap_limit: 256m   # = mem_limit -> sin swap
    mem_swappiness: 0
    volumes:
      - fixed_data:/data/uploads

volumes:
  vulnerable_data:
  fixed_data: